---
title: "🎉 Presentaciones"
output: html_document
---

# Lista de Presentaciones

¡Hola! Aquí tienes una lista de nuestras presentaciones, realizadas con [Quarto](https://quarto.org/), una herramienta poderosa para crear documentos y presentaciones dinámicas en diferentes formatos.

| Título                                                                                                                | Descripción                                                                                                     | Presentaciones                                                                                                                                                               |
|------------------|---------------------------|---------------------------|
| [Crea, Innova y Presenta: Data Storytelling con A.I.](visualization_2024/presentacion.html)                           | Transforma datos en historias visuales interactivas usando A.I. y herramientas dinámicas.                       | [Nerdearla (ES) 2025](shiny_2025/presentacion_ne.html), [Pycon (COL) 2025](shiny_2025/presentacion_pc.html), <br> [PyLadiesCon 2025](visualization_2024/presentacion_pyladies.html)                                                  |
| [Narrativas con Datos - BDO](shiny_2025/presentacion_ext.html)                                                        | Crear presentaciones persuasivas con datos que capten, mantengan y movilicen a la audiencia.                    | [Ñuble Alimentos](shiny_2025/presentacion_ext.html), <br> [Fondo Esperanza I](shiny_2025/presentacion_fa1.html), <br> [Fondo Esperanza II](shiny_2025/presentacion_fa2.html) |
| [Del Dato a la Narrativa: Visualización Interactiva con Shiny](shiny_2025/presentacion_es.html)                       | Aprende a crear paneles interactivos y visualizaciones narrativas con Shiny.                                    | [ShinyConf 2025](shiny_2025/presentacion.html), <br> [UserR 2025](shiny_2025/presentacion_user.html)                                                                         |
| [No es Magia, es Ciencia](prompts_chatgpt/presentacion.html)                                                          | Aprende a estructurar prompts efectivos para herramientas como ChatGPT de forma precisa y ética.                | [TechSchool 2025](prompts_chatgpt/presentacion.html),<br> [EMMA Agosto 2025](prompts_chatgpt/presentacion_emma.html)                                                         |
| [Hola Quarto - compartir • colaborar • enseñar • reimaginar](hello-quarto/presentacion.html)                          | Taller introductorio a Quarto, una herramienta para crear documentos, presentaciones y sitios web interactivos. | [Sumemos Ideas: Seminarios USM](hello-quarto/presentacion.html),<br> [Pycon Chile 2025](hello-quarto/presentacion_pycon.html)                                                |
| [¡Adiós Word, Hola LaTeX!](latex_2025/presentacion.html)                                                              | Taller práctico para descubrir LaTeX como alternativa profesional a Word.                                       | [EMMA Agosto 2025](latex_2025/presentacion_emma.html)                                                                                                                        |
| [Pyday 2025 - Educación Abierta y Comunidad](comunidad_2025/presentacion.html)                                        | Crea y comparte contenidos educativos colaborando con profesionales usando GitHub y Quarto.                     | [Presetación](comunidad_2025/presentacion.html)                                                                                                                              |
| [LatinR 2024 - Uso de Quarto para crear clases interactivas](latinr_2024/presentacion.html)                           | Quarto permite diseñar contenidos interactivos en R y Python.                                                   | [Presetación](latinr_2024/presentacion.html)                                                                                                                                 |
| [MADS USM 2024 - Inteligencia Artificial en la Educación](mads_2024/presentacion.html)                                | Aplicaciones prácticas de la IA en la enseñanza para experiencias personalizadas.                               | [Presetación](mads_2024/presentacion.html)                                                                                                                                   |
| [DMAT USM 2024 - Más allá del Infinito](infinity_2024/presentacion.html)                                              | Explora los conceptos del infinito en matemáticas con ejemplos interactivos.                                    | [Presetación](infinity_2024/presentacion.html)                                                                                                                               |
| [II Encuentro Docencia Matemática Universitaria - Innovación en el curso MAT281](uc_2024/presentacion.html)           | Cómo Google Colab y evaluaciones interactivas transformaron la experiencia educativa del curso.                 | [Presetación](uc_2024/presentacion.html)                                                                                                                                     |
| [Narrativas con Datos](narrativas_2024/presentacion.html)                                                             | Aprende a contar historias persuasivas con datos usando Python y visualización.                                 | [Presetación](narrativas_2024/presentacion.html)                                                                                                                             |
| [Conéctate al Mundo Digital: Computación para Personas Mayores desde Cero](computacion_2024/presentacion.html)        | Introducción accesible al uso de la tecnología para personas mayores.                                           | [Presetación](computacion_2024/presentacion.html)                                                                                                                            |
| [¿Y Ahora Qué? Del Aula al Trabajo](profesional_2024/presentacion.html)                                               | Habilidades clave y herramientas para la transición al mundo laboral.                                           | [Presetación](profesional_2024/presentacion.html)                                                                                                                            |
| [Educación sin Límites: Automatiza tus Contenidos Interactivos con Quarto y GitHub](pycon_usa_2025/presentacion.html) | Automatiza y comparte materiales educativos con GitHub y Quarto.                                                | [Presetación](pycon_usa_2025/presentacion.html)                                                                                                                              |